all:
  children:
    genz_servers:
      hosts:
        server1:
          ansible_host: "13.92.154.156"
          ansible_user: "azureuser"
          ansible_ssh_private_key_file: "/tmp/ansible_key.pem"